
### Update Learning Outcome - CSS Fundamentals
PUT http://127.0.0.1:8000/api/courses/learning-outcomes/css-fundamentals/update/
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMjc3MDAyLCJpYXQiOjE3NjAyNjk4MDIsImp0aSI6IjgwM2JlNzk4OTQ5MTQ4MmJhNGZkNjE4YjI1MmNjMDRlIiwidXNlcl9pZCI6IjI5In0.STHp4n1KdxholJoL6SUp4TkUR8ibgZcak2H5AdAHZEE

{
    "description": "CSS COLORS AND Fundamentals"
}

### GET Course Learning Outcome 
GET http://127.0.0.1:8000/api/courses/learning-outcomes/course-test-2/CDCC57E54A154B10
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMjc3MDAyLCJpYXQiOjE3NjAyNjk4MDIsImp0aSI6IjgwM2JlNzk4OTQ5MTQ4MmJhNGZkNjE4YjI1MmNjMDRlIiwidXNlcl9pZCI6IjI5In0.STHp4n1KdxholJoL6SUp4TkUR8ibgZcak2H5AdAHZEE

{
    "description": "CSS COLORS AND Fundamentals"
}

### GET Course Learning Outcome 
GET http://127.0.0.1:8000/auth/users/me/
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwNDYwNDM3LCJpYXQiOjE3NjA0NTMyMzgsImp0aSI6IjI3YjUzMmY0Y2MxNDQ0MDM4NDE4NGY3YThiMzQzYmQ4IiwidXNlcl9pZCI6IjQwIn0.F9hZ-N6YMUWdwPeEVsKdMZMLGSa-_f9jV-S1KEG7xQ0

