# Generated by Django 5.2.6 on 2025-10-25 17:49

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Development & Programming', 'Development & Programming'), ('Business & Management', 'Business & Management'), ('Finance & Accounting', 'Finance & Accounting'), ('IT & Software', 'IT & Software'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Personal Development', 'Personal Development'), ('Photography & Video', 'Photography & Video'), ('Music & Audio', 'Music & Audio'), ('Health & Fitness', 'Health & Fitness'), ('Teaching & Academics', 'Teaching & Academics'), ('Language Learning', 'Language Learning'), ('Data Science & Analytics', 'Data Science & Analytics'), ('Artificial Intelligence & Machine Learning', 'Artificial Intelligence & Machine Learning'), ('Cloud Computing & DevOps', 'Cloud Computing & DevOps'), ('Cybersecurity', 'Cybersecurity'), ('Engineering', 'Engineering'), ('Science & Mathematics', 'Science & Mathematics'), ('Social Sciences', 'Social Sciences'), ('Humanities', 'Humanities'), ('Lifestyle', 'Lifestyle'), ('Cooking & Culinary Arts', 'Cooking & Culinary Arts'), ('Arts & Crafts', 'Arts & Crafts'), ('Beauty & Makeup', 'Beauty & Makeup'), ('Sports', 'Sports'), ('Travel & Adventure', 'Travel & Adventure'), ('Test Preparation', 'Test Preparation'), ('Career Development', 'Career Development'), ('Parenting & Relationships', 'Parenting & Relationships')], default='Development & Programming', max_length=100)),
                ('slug', models.SlugField(default='', max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('promo_video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('is_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(default='', max_length=500, unique=True)),
                ('token', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_puplished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=160, verbose_name='Outcome Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Learning OutComes',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('is_preview', models.BooleanField(default=False)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default='', max_length=500)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Vary Good'), (5, '5 - Excellent')], null=True)),
                ('body', models.TextField(max_length=300)),
                ('slug', models.SlugField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
