# Generated by Django 5.1.7 on 2025-04-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_loves_alter_course_promo_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='courses/videos/lesson_images/'),
            preserve_default=False,
        ),
    ]
