# Generated by Django 5.2.6 on 2025-10-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='thumbnail',
        ),
    ]
