# Generated by Django 5.1.7 on 2025-04-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_lesson_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_published',
        ),
    ]
