# Generated by Django 5.1.7 on 2025-04-09 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_lesson_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
