# Generated by Django 5.1.7 on 2025-04-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_lesson_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
