# Generated by Django 5.1.7 on 2025-04-14 23:40

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_level_lesson_duration'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
