# Generated by Django 5.1.7 on 2025-04-16 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_learning_outcomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='learning_outcomes',
        ),
        migrations.CreateModel(
            name='LearningOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=160, verbose_name='Outcome Description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sorting Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outcomes', to='course.course')),
            ],
        ),
    ]
