# Generated by Django 5.1.7 on 2025-04-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_remove_course_learning_outcomes_learningoutcomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningoutcomes',
            name='order',
        ),
    ]
