# Generated by Django 5.1.7 on 2025-04-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_learningoutcomes_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcomes',
            name='description',
            field=models.CharField(max_length=160, verbose_name='Outcome Description'),
        ),
    ]
