# Generated by Django 5.1.7 on 2025-04-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_learningoutcomes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcomes',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
