# Generated by Django 5.1.7 on 2025-04-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_learningoutcomes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
