# Generated by Django 5.2.4 on 2025-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_category_views'),
        ('members', '0006_alter_instructor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='viewers',
            field=models.ManyToManyField(related_name='cat_viewers', to='members.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='viewers',
            field=models.ManyToManyField(related_name='course_viewers', to='members.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
