# Generated by Django 5.2.4 on 2025-07-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_category_viewers_course_viewers_course_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='viewers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='viewers',
        ),
    ]
