# Generated by Django 5.2.4 on 2025-07-23 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_remove_category_viewers_remove_course_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='course.course'),
        ),
    ]
