# Generated by Django 5.2.4 on 2025-07-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_course_views_alter_enrollment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
