# Generated by Django 5.2.4 on 2025-07-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_course_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='views',
        ),
        migrations.AddField(
            model_name='lesson',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
