# Generated by Django 5.2.4 on 2025-08-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_alter_review_course_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
