# Generated by Django 5.2.4 on 2025-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_course_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
