# Generated by Django 5.2.4 on 2025-08-03 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0026_course_thumbnail"),
        ("members", "0006_alter_instructor_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
