# Generated by Django 5.2.4 on 2025-08-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_remove_review_rating_review_body_review_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='learningoutcomes',
            options={'verbose_name_plural': 'Learning OutComes'},
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/category_images/'),
        ),
    ]
