# Generated by Django 5.2.4 on 2025-08-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_alter_enrollment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='preview',
            new_name='is_preview',
        ),
    ]
