# Generated by Django 5.2.4 on 2025-08-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_rename_preview_lesson_is_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_enrolled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
