# Generated by Django 5.2.4 on 2025-08-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_enrollment_is_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_enrolled',
        ),
    ]
