# Generated by Django 5.2.4 on 2025-08-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_alter_enrollment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='user',
        ),
    ]
