# Generated by Django 5.2.4 on 2025-08-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_rename_student_enrollment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='user',
            new_name='student',
        ),
    ]
