# Generated by Django 5.2.4 on 2025-08-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0038_rename_student_enrollment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
