# Generated by Django 5.2.4 on 2025-08-09 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_alter_review_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
