# Generated by Django 5.2.4 on 2025-08-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_contact_user'),
        ('members', '0006_alter_instructor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_courses', to='members.instructor'),
        ),
    ]
