# Generated by Django 5.2.4 on 2025-08-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0042_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
