# Generated by Django 5.2.4 on 2025-08-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0043_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='views',
        ),
    ]
