# Generated by Django 5.2.4 on 2025-08-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0045_review_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
