# Generated by Django 5.2.4 on 2025-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='category',
            name='views',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Development & Programming', 'Development & Programming'), ('Business & Management', 'Business & Management'), ('Finance & Accounting', 'Finance & Accounting'), ('IT & Software', 'IT & Software'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Personal Development', 'Personal Development'), ('Photography & Video', 'Photography & Video'), ('Music & Audio', 'Music & Audio'), ('Health & Fitness', 'Health & Fitness'), ('Teaching & Academics', 'Teaching & Academics'), ('Language Learning', 'Language Learning'), ('Data Science & Analytics', 'Data Science & Analytics'), ('Artificial Intelligence & Machine Learning', 'Artificial Intelligence & Machine Learning'), ('Cloud Computing & DevOps', 'Cloud Computing & DevOps'), ('Cybersecurity', 'Cybersecurity'), ('Engineering', 'Engineering'), ('Science & Mathematics', 'Science & Mathematics'), ('Social Sciences', 'Social Sciences'), ('Humanities', 'Humanities'), ('Lifestyle', 'Lifestyle'), ('Cooking & Culinary Arts', 'Cooking & Culinary Arts'), ('Arts & Crafts', 'Arts & Crafts'), ('Beauty & Makeup', 'Beauty & Makeup'), ('Sports', 'Sports'), ('Travel & Adventure', 'Travel & Adventure'), ('Test Preparation', 'Test Preparation'), ('Career Development', 'Career Development'), ('Parenting & Relationships', 'Parenting & Relationships')], default='Development & Programming', max_length=100),
        ),
    ]
