# Generated by Django 5.2.4 on 2025-08-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0047_remove_category_thumbnail_remove_category_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='learningoutcomes',
            name='slug',
            field=models.SlugField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(default='', max_length=500, unique=True),
        ),
    ]
