# Generated by Django 5.2.4 on 2025-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0048_alter_category_slug_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(default='', max_length=500),
        ),
    ]
