# Generated by Django 5.1.7 on 2025-04-03 16:56

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=255)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='users/profile_images/%Y/%m/%d/', verbose_name='profile_picture')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('birth_date', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('token', models.CharField(blank=True, max_length=20, unique=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=500, null=True)),
                ('website_url', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedIn_url', models.CharField(blank=True, max_length=500, null=True)),
                ('teaching_exe', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 year'), (2, '2 years'), (3, '3 years'), (4, '4 years'), (5, '5+ years')], default=1)),
                ('followers', models.ManyToManyField(blank=True, related_name='instructor_follower', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=255)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='users/profile_images/%Y/%m/%d/', verbose_name='profile_picture')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('birth_date', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('token', models.CharField(blank=True, max_length=20, unique=True)),
                ('enrollments', models.CharField(blank=True, max_length=500, null=True)),
                ('courses_complete', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
