# Generated by Django 5.2.6 on 2025-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='slug',
            field=models.SlugField(default='', max_length=1500),
        ),
    ]
