# Generated by Django 5.1.7 on 2025-04-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_instructor_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'permissions': [('add_course', 'Can add course'), ('change_course', 'Can change course'), ('delete_course', 'Can delete course')]},
        ),
    ]
