# Generated by Django 5.2.6 on 2025-10-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='teaching_exe',
            field=models.CharField(blank=True, choices=[('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5+ years')], default='1', max_length=50),
        ),
    ]
