# Generated by Django 5.1.7 on 2025-04-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_instructor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'permissions': [('add_course', 'Can add course'), ('change_course', 'Can change course'), ('delete_course', 'Can delete course'), ('add_module', 'Can add module'), ('change_module', 'Can update module'), ('delete_module', 'Can delete course')]},
        ),
    ]
