# Generated by Django 5.2.4 on 2025-08-16 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_instructor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='linkedIn_url',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='website_url',
        ),
        migrations.CreateModel(
            name='SocialLinkes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.instructor')),
            ],
        ),
    ]
