# Generated by Django 5.2.4 on 2025-08-16 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_instructor_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_links', to='members.instructor')),
            ],
        ),
        migrations.DeleteModel(
            name='SocialLinkes',
        ),
    ]
