# Generated by Django 5.2.4 on 2025-08-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_sociallinks_delete_sociallinkes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='link',
            field=models.URLField(max_length=250),
        ),
    ]
