# Generated by Django 5.2.4 on 2025-08-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_sociallinks_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
    ]
