# Generated by Django 5.2.4 on 2025-08-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_instructor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='about',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
