# Generated by Django 5.2.4 on 2025-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_instructor_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
