from django.urls import path

from .views import (
    About,
    AddLessonView,
    CourseDetail,
    CoursesList,
    CreateCourse,
    CreateLearningObjectives,
    CreateModule,
    DeleteCourse,
    DeleteLearningObjectives,
    DeleteLesson,
    DeleteModule,
    EditLearningObjectives,
    EditLesson,
    EditModule,
    Index,
    UpdateCourse,
    best_seller,
    create_contact,
    create_review,
    draft_modules,
    fetch_courses_by_category,
    fetch_courses_by_tag,
    remove_contact,
    remove_review,
    search,
    top_courses,
    top_instructors,
    update_contact,
    update_review,
    user_contact_messages,
    modules,
)

app_name = "course"
urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("about/", About.as_view(), name="about"),
    path("create-course/", CreateCourse.as_view(), name="create-course"),
    path(
        "update-course/<slug:slug>/<str:token>/",
        UpdateCourse.as_view(),
        name="update-course",
    ),
    path(
        "delete-course/<slug:slug>/<str:token>/",
        DeleteCourse.as_view(),
        name="delete-course",
    ),
    path(
        "create-course/create-objectives/<slug:slug>/<str:token>/",
        CreateLearningObjectives.as_view(),
        name="create-learning-objectives",
    ),
    path(
        "create-course/edit-objective/<slug:slug>/",
        EditLearningObjectives.as_view(),
        name="edit-learning-objective",
    ),
    path(
        "create-course/delete-objective/<slug:slug>/",
        DeleteLearningObjectives.as_view(),
        name="delete-learning-objective",
    ),
    path(
        "create-course/create-module/<slug:slug>/<str:token>/",
        CreateModule.as_view(),
        name="create-module",
    ),
    path(
        "create-course/edit-module/<slug:slug>/",
        EditModule.as_view(),
        name="edit-module",
    ),
    path(
        "create-course/delete-module/<slug:slug>/",
        DeleteModule.as_view(),
        name="delete-module",
    ),
    path("draft-modules/<str:course_token>/", draft_modules, name="draft-modules"),
    path("modules/<str:course_token>/", modules, name="modules"),
    path(
        "create-course/module/create-lesson/<slug:slug>/",
        AddLessonView.as_view(),
        name="create-lesson",
    ),
    path(
        "create-course/module/edit-lesson/<slug:slug>/<str:token>",
        EditLesson.as_view(),
        name="edit-lesson",
    ),
    path(
        "create-course/module/delete-lesson/<slug:slug>/<str:token>",
        DeleteLesson.as_view(),
        name="delete-lesson",
    ),
    path(
        "course-detail/<slug:slug>/<str:token>/",
        CourseDetail.as_view(),
        name="course-detail",
    ),
    path("search/", search, name="search"),
    path("courses/", CoursesList.as_view(), name="courses-list"),
    path(
        "categories/<str:slug>/",
        fetch_courses_by_category,
        name="fetch-courses-by-category",
    ),
    path("tags/<str:tag>/", fetch_courses_by_tag, name="fetch-courses-by-tag"),
    # review paths
    path("create-review/<str:token>/", create_review, name="create-review"),
    path("update-review/<slug:slug>/", update_review, name="update-review"),
    path("remove-review/<slug:slug>/", remove_review, name="remove-review"),
    # contact paths
    path("user-contacts/", user_contact_messages, name="user-contact-messages"),
    path("contact/", create_contact, name="contact"),
    path("update-contact/<str:token>/", update_contact, name="update-contact"),
    path("remove-contact/<str:token>/", remove_contact, name="remove-contact"),
    # trending now paths
    path("top-courses/", top_courses, name="top-courses"),
    path("best-seller/", best_seller, name="best-seller"),
    path("top-instructors/", top_instructors, name="top-instructors"),
]
